# Generated by Django 3.1.7 on 2021-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inCart',
            field=models.BooleanField(default=False),
        ),
    ]
