# Generated by Django 3.1.7 on 2021-05-28 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 28, 21, 53, 42, 752777))),
                ('duration', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('virtual', 'virtual'), ('in person', 'in person'), ('other', 'other')], default='virtual', max_length=32)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_talk', models.BooleanField(default=False)),
                ('salary', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('applied', 'applied'), ('first interview', 'first interview'), ('second interview', 'second interview'), ('third interview', 'third interview'), ('offer', 'offer')], default='applied', max_length=32)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobhunt.interview')),
            ],
        ),
    ]
