# Generated by Django 3.1.7 on 2021-05-28 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview',
        ),
        migrations.AddField(
            model_name='interview',
            name='Job_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobhunt.jobapplication'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 22, 6, 19, 344746)),
        ),
    ]
