# Generated by Django 3.1.7 on 2021-05-28 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0002_auto_20210528_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 28, 22, 24, 14, 758678))),
            ],
        ),
        migrations.CreateModel(
            name='Techstack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='Job_application',
            new_name='job_application',
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 22, 24, 14, 758678)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='platform',
            field=models.CharField(choices=[('google meet', 'google meet'), ('zoom', 'zoom'), ('microsoft teams', 'microsoft teams'), ('other', 'other')], default='google hangout', max_length=32),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('first interview', 'first interview'), ('second interview', 'second interview'), ('third interview', 'third interview'), ('final offer', 'final offer')], default='applied', max_length=32),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobhunt.techstack'),
        ),
    ]
