# Generated by Django 3.1.7 on 2021-05-28 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0003_auto_20210528_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='tech',
        ),
        migrations.AddField(
            model_name='schedule',
            name='job_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobhunt.jobapplication'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='job_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobhunt.jobapplication'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 22, 33, 36, 296419)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 22, 33, 36, 297463)),
        ),
    ]
