# Generated by Django 3.1.7 on 2021-05-29 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0005_auto_20210528_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 9, 30, 28, 333487)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 9, 30, 28, 334490)),
        ),
    ]
