# Generated by Django 3.1.7 on 2021-05-29 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0008_auto_20210529_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 8, 38, 16, 415515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 8, 38, 16, 417513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 8, 38, 16, 418516, tzinfo=utc)),
        ),
    ]
