# Generated by Django 3.1.7 on 2021-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0011_interview_verdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='application',
            name='salary_talk',
        ),
        migrations.AddField(
            model_name='interview',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='salary_talk',
            field=models.BooleanField(default=False),
        ),
    ]
