# Generated by Django 3.1.7 on 2021-06-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0012_auto_20210603_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='techstack',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techstack', to='jobhunt.application'),
        ),
    ]
