# Generated by Django 3.1.7 on 2021-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0013_auto_20210606_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='interview',
            name='salary',
            field=models.IntegerField(default=45000),
        ),
    ]
