# Generated by Django 3.1.7 on 2021-06-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt', '0014_auto_20210608_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
